# Numpy tutorial walkthrough with DSMP

In [4]:
# creating a numpy array
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
#2d and 3d array

b = np.array([[1, 2, 3],[4,5,7]])
print(b, "\n")

c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(c)

[[1 2 3]
 [4 5 7]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
#dtype : set a datatype for the array
a = np.array([0, 1, 3, 5], dtype=float)
b = np.array([0, 1, 3, 5], dtype=bool)
c = np.array([0, 1, 3, 5], dtype=complex)
print(a)
print(b)
print(c)

[0. 1. 3. 5.]
[False  True  True  True]
[0.+0.j 1.+0.j 3.+0.j 5.+0.j]


In [33]:
# np.a-range
a = np.arange(1, 10, )
print(a)
a = np.arange(1, 10, 2)
print(a)


#arange with reshape
b = np.arange(1, 11).reshape(5, 2)
print(b)

#making 4d array
c = np.arange(16).reshape(2,2,2,2)
print("c : \n",c)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
c : 
 [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [25]:
#np.ones and #np.zeroes and #np.random
ones = np.ones((3, 4))
print(ones)

zeros = np.zeros((3, 4))
print(zeros)

rand = np.random.random((3, 4))
print(rand)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.13535297 0.77569594 0.8947757  0.60613332]
 [0.88873302 0.26455891 0.09598918 0.44037116]
 [0.5745408  0.3596376  0.13516426 0.68036395]]


In [28]:
#np.linspace : linear space : random numbers between a range, at equal distance
a = np.linspace(-10, 10, 10)
print(a)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [29]:
#np.identity
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Numpy attributes

In [37]:
a = np.arange(10)
b = np.arange(12, dtype=float).reshape(3,4)
c = np.arange(8).reshape(2,2,2)

In [38]:
#ndim : number of dimensions
print("a", a.ndim)
print("b", b.ndim)
print("c", c.ndim)

a 1
b 2
c 3


In [39]:
#shape 
print("a", a.shape)
print("b", b.shape)
print("c", c.shape)

a (10,)
b (3, 4)
c (2, 2, 2)


In [40]:
#size : number of items
print("a", a.size)
print("b", b.size)
print("c", c.size)

a 10
b 12
c 8


In [41]:
#itemsize : size in memory in bytes for each item
print("a", a.itemsize)
print("b", b.itemsize)
print("c", c.itemsize)

a 8
b 8
c 8


In [42]:
#dtype : datatype of elements
print("a", a.dtype)
print("b", b.dtype)
print("c", c.dtype)

a int64
b float64
c int64


In [45]:
#changing datatype
print("c : " , c.dtype)
d = c.astype(np.int32)
print("d : " , d.dtype)

c :  int64
d :  int32


## Numpy Array operations

In [48]:
a = np.arange(12).reshape(3,4)
b = np.arange(12, 24).reshape(3,4)

In [53]:
#scalar operations

#arithmetic
print(a*2, "\n")

#relational
print(b, b>20, sep="\n")

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[False False False False]
 [False False False False]
 [False  True  True  True]]


In [56]:
#vector operations

#arithmetic
print(a+b)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


## Numpy array function

In [63]:
a = np.random.random((3,3))
a = np.round(a*100)
print(a)

[[27.  7. 16.]
 [22. 57. 61.]
 [65. 87. 86.]]


In [68]:
# max, min, sum, prod
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.prod(a))

#axis : 0 = column, 1 = row
print(np.max(a, axis = 1))
print(np.max(a, axis = 0))

87.0
7.0
428.0
112496812908480.0
[27. 61. 87.]
[65. 87. 86.]


In [70]:
# mean, median, std, variance
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

47.55555555555556
57.0
28.52722329873348
813.8024691358024


In [73]:
# trigonometric functions
print(np.sin(a), "\n")
print(np.cos(a), "\n")
print(np.tan(a), "\n")

[[ 0.95637593  0.6569866  -0.28790332]
 [-0.00885131  0.43616476 -0.96611777]
 [ 0.82682868 -0.82181784 -0.92345845]] 

[[-0.29213881  0.75390225 -0.95765948]
 [-0.99996083  0.89986683 -0.25810164]
 [-0.56245385  0.56975033 -0.38369844]] 

[[-3.2737038   0.87144798  0.30063224]
 [ 0.00885166  0.48469923  3.74316794]
 [-1.47003826 -1.44241747  2.40672971]] 



In [74]:
# dot product
b = np.arange(12).reshape(3,4)
c = np.arange(12, 24).reshape(4,3)

print(np.dot(b, c))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [76]:
#log and exponents
print(np.log(a))
print(np.exp(a))

[[3.29583687 1.94591015 2.77258872]
 [3.09104245 4.04305127 4.11087386]
 [4.17438727 4.46590812 4.4543473 ]]
[[5.32048241e+11 1.09663316e+03 8.88611052e+06]
 [3.58491285e+09 5.68572000e+24 3.10429794e+26]
 [1.69488924e+28 6.07603023e+37 2.23524660e+37]]


In [80]:
# round, floor, ceil
c = np.random.random((2,3))
print(c)
d = np.round(c*100)
print(d)
d = np.floor(c*100)
print(d)
d = np.ceil(c*100)
print(d)

[[0.85914186 0.15514526 0.73830378]
 [0.64096638 0.1336237  0.95059583]]
[[86. 16. 74.]
 [64. 13. 95.]]
[[85. 15. 73.]
 [64. 13. 95.]]
[[86. 16. 74.]
 [65. 14. 96.]]


## Indexing and Slicing

In [107]:
a = np.arange(10)
b = np.arange(12, dtype=float).reshape(3,4)
c = np.arange(27).reshape(3,3,3)

In [82]:
print(a)

#negative indexing
print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
9


In [84]:
print(b)

# getting element 6
print(b[1][2])



[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
6.0


In [86]:
print(c)

# getting element 6
print(c[1][1][0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
6


In [95]:
# slicing
print(a[2:5])

#slicing with steps
print(a[2:5:2])

#first row of 2d array
print(b[0])

#first row and all cols of 2d array
print(b[0,:])

# only the third col
print(b[:,2])

[2 3 4]
[2 4]
[0. 1. 2. 3.]
[0. 1. 2. 3.]
[ 2.  6. 10.]


In [104]:
print(b)
# getting 5, 6, 9, 10
print(b[1:, 1:3])

# getting 0, 3, 8, 11
# first we get alternate rows
# first we get cols with gap 2
print(b[::2, ::3])

# getting 1, 3, 9, 11
print(b[::2, 1::2])

# getting 4, 7
print(b[1, ::3])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 5.  6.]
 [ 9. 10.]]
[[ 0.  3.]
 [ 8. 11.]]
[[ 1.  3.]
 [ 9. 11.]]
[4. 7.]


In [118]:
print(c, "\n\n")

# the middle 2d array
print(c[1])

# second row of 1st 2d array : 3, 4, 5
print(c[0][1])
print(c[0, 1])

# getting 10, 13, 16
print(c[1, :, 1 ])

# getting matrix 22 23 25 26
print(c[2, 1:, 1:])

# ### getting 0, 2, 18, 20
print(c[::2, 0, ::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[3 4 5]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


## iterating

In [120]:
print(a)
for i in a : 
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [126]:
print(b)
for i in b : 
    print(i)
    
for i in np.nditer(b):
    print(i)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [127]:
print(c)
for i in c : 
    print (i)
    
for i in np.nditer(c):
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping : reshape, transpose, ravel

In [131]:
print(b)

#reshape
print(b.reshape(6,2))

# transpose
print(b.T) #or
print(np.transpose(b))

#ravel : converts n dimension array to 1d
print(b.ravel())
print(c.ravel())

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]
[[ 0.  4.  8.]
 [ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]]
[[ 0.  4.  8.]
 [ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


## stacking : joining arrays (same shape required)

In [133]:
# horizontal stacking
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12, 24).reshape(3,4)
print(a1, a2)
print(np.hstack((a1, a2, a1, a2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15  0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19  4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23  8  9 10 11 20 21 22 23]]


In [134]:
# vertical stacking
print(np.vstack((a1,a2,a1,a2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Splitting

In [139]:
# horizontal splitting (we have to provide parts)
d = np.hstack((a1, a2, a1, a2))
print(d)
print(np.hsplit(d, 4))

# vertical splitting
#print(np.vsplit(b, 2))

[[ 0  1  2  3 12 13 14 15  0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19  4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23  8  9 10 11 20 21 22 23]]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]


ValueError: array split does not result in an equal division